[common]
  host="http://remote.fzf404.top" # host
  port = 8080 # 端口
  
[jwt]
  key = "fzf404-todolist-secret" # 签名密钥
  expires = 604800 # 过期时间(秒)
  issuer = "fzf404" # 发行人

[mysql]
  username = "root"
  password = "fzf404"
  host = "127.0.0.1"
  port = 3306
  database = "TodoList"
  config = "charset=utf8&parseTime=true"

[todo]
  page = 8 # 每页 Todo 条数